# Generated by Django 5.2.5 on 2025-08-16 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detailview", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="participation",
            name="is_standby",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="party",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                fields=("party", "user"), name="unique_participation_per_party"
            ),
        ),
    ]
