# Generated by Django 5.2.5 on 2025-08-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-17 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participation',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='결제일시'),
        ),
        migrations.AddField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', '결제 대기'), ('CONFIRMED', '참가 확정'), ('CANCELED', '참가 취소')], default='PENDING_PAYMENT', max_length=20, verbose_name='상태'),
        ),
        migrations.AddField(
            model_name='party',
            name='deposit',
            field=models.PositiveIntegerField(default=0, verbose_name='예약금'),
        ),
    ]
