# Generated by Django 5.2.5 on 2025-08-18 01:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("detailview", "0002_alter_participation_unique_together_and_more"),
        ("detailview", "0002_participation_created_at_participation_paid_at_and_more"),
    ]

    operations = []
