# Generated by Django 5.2.5 on 2025-08-16 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detailview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_used', models.CharField(default='gpt-4o-mini', max_length=40, verbose_name='사용 모델')),
                ('safety_blocked', models.BooleanField(default=False, verbose_name='안전성 차단')),
                ('safety_reason', models.CharField(blank=True, default='', max_length=120, verbose_name='차단 사유')),
                ('is_active', models.BooleanField(default=True, verbose_name='진행 중')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_balance_rounds', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_rounds', to='detailview.party', verbose_name='파티')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BalanceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='표시 순서')),
                ('a_text', models.CharField(max_length=80, verbose_name='선택지 A')),
                ('b_text', models.CharField(max_length=80, verbose_name='선택지 B')),
                ('vote_a_count', models.PositiveIntegerField(default=0, verbose_name='A 득표')),
                ('vote_b_count', models.PositiveIntegerField(default=0, verbose_name='B 득표')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game.balanceround', verbose_name='라운드')),
            ],
            options={
                'ordering': ['round', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BalanceVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1, verbose_name='선택')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='game.balancequestion', verbose_name='문항')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_votes', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='balanceround',
            index=models.Index(fields=['created_at'], name='game_balanc_created_7d4cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='balancequestion',
            index=models.Index(fields=['round', 'order'], name='game_balanc_round_i_f8fc4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='balancequestion',
            constraint=models.UniqueConstraint(fields=('round', 'order'), name='uniq_round_order'),
        ),
        migrations.AddIndex(
            model_name='balancevote',
            index=models.Index(fields=['user'], name='game_balanc_user_id_0ba8d1_idx'),
        ),
        migrations.AddIndex(
            model_name='balancevote',
            index=models.Index(fields=['question'], name='game_balanc_questio_f78f38_idx'),
        ),
        migrations.AddConstraint(
            model_name='balancevote',
            constraint=models.UniqueConstraint(fields=('question', 'user'), name='uniq_vote_per_user_question'),
        ),
    ]
