# Generated by Django 5.2.5 on 2025-08-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="notice_type",
            field=models.CharField(
                choices=[
                    ("party_open_1day", "파티 오픈 1일 전"),
                    ("party_insufficient", "인원 미달 오픈 1일 전"),
                    ("party_new", "새 파티 생성"),
                    ("party_applied", "파티 신청 완료"),
                    ("party_canceled", "파티 신청 취소"),
                ],
                max_length=50,
            ),
        ),
    ]
