# Generated by Django 5.2.5 on 2025-08-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("POINT", "포인트"), ("COUPON", "쿠폰"), ("CARD", "카드결제")],
                default="POINT",
                max_length=20,
                verbose_name="결제 방법",
            ),
        ),
    ]
