# Generated by Django 5.2.5 on 2025-08-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="nickname",
        ),
        migrations.AddField(
            model_name="user",
            name="intro",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="한줄소개"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="이름"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="전화번호"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/", verbose_name="프로필 사진"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="학교"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="student_card_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="student_cards/", verbose_name="학생증 사진"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="warnings",
            field=models.PositiveIntegerField(default=0, verbose_name="경고 횟수"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="이메일"
            ),
        ),
    ]
