# Generated by Django 5.2.5 on 2025-08-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_nickname_user_intro_user_name_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="points",
            field=models.PositiveIntegerField(default=10000, verbose_name="포인트"),
        ),
    ]
